import { Container } from "@mantine/core";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { FileUploadSection } from "~/components/FileUploadSection";
import { RecomendedGlasses } from "~/components/RecomendedGlases/RecomendedGlasses";

export default function Home() {
  const router = useRouter();
  const { requestId = null } = router.query;
  const [loadedRequest, setLoadedRequest] = useState<string | string[] | null>(
    null
  );
  // Get the request and list glasses for the faceType
  useEffect(() => {
    if (window != undefined) {
      const storedRequest = localStorage.getItem("requestId");
      setLoadedRequest(storedRequest ?? requestId);
    }
  }, [requestId]);

  return (
    <>
      <Head>
        <title>Send your photo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#1c2046] to-[#18140b]">
        <Container>
          {loadedRequest != null ? (
            <RecomendedGlasses />
          ) : (
            <FileUploadSection />
          )}
        </Container>
      </main>
    </>
  );
}
