import { Button, FileButton, Group, Text, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const form = useForm({
    initialValues: {
      file: null,
      name: "",
    },
  });

  useEffect(() => {
    setFile(form.values.file);
  }, [form.values.file]);

  return (
    <>
      <Head>
        <title>Snend your photo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Send your photo
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <form onSubmit={form.onSubmit((values) => console.log(values))}>
              <>
                <Group position="center">
                  <FileButton
                    accept="image/png,image/jpeg"
                    {...form.getInputProps("file")}
                  >
                    {(props) => <Button {...props}>Upload image</Button>}
                  </FileButton>
                </Group>

                {file && (
                  <Text size="sm" align="center" mt="sm">
                    Picked file: {file.name}
                  </Text>
                )}
              </>
              <Button type="submit">Send!</Button>
            </form>
          </div>
          <AuthShowcase />
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
